apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: cert-manager-secretstore
  namespace: cert-manager
spec:
  provider:
    vault:
      server: "http://vault-server.vault-server.svc.cluster.local:8200"
      path: "pki"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "host-cluster"
          # A required field containing the Vault Role to assume.
          role: "cert-manager"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "default"
